### ISSUE TITLE
Node 0.6.0 compatibility

### ISSUE THREAD

**Issue by ghost** [Gozala/crypto#1]
Can you update please for Node 0.6.x?

**Comment by Gozala** [comment]
Done: https://github.com/Gozala/crypto/commit/d4b4858e9e49fa032841c4f703390d561326c205

**Comment by Gozala** [comment]
Done! 

## Regards

Irakli Gozalishvili
Web: http://www.jeditoolkit.com/
Address: 29 Rue Saint-Georges, 75009 Paris, France (http://goo.gl/maps/3CHu)
